export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILE = 'LOGIN_FAILE';
export const LOGIN_FROM_LOCALESTORAGE = 'LOGIN_FROM_LOCALESTORAGE';
